### ISSUE TITLE
AT command CWLAP

### ISSUE THREAD

**Issue by AndrewP79** [JiriBilek/ESP_ATMod#2]
Hi, i have tested on ESP01S, i have sent a message to Telegram opening connection with AT+CIPSTART="SSL","api.telegram.org",443 and sent to chat id my message, all fine. :)

but maybe command for list of available network is not implemented? How to add it? 

Thank you for your job.

**Comment by JiriBilek** [comment]
Hi,
indeed, the command AT+CWLAP is not yet implemented. It is not quite easy as the command is asynchronous by nature.

**Comment by AndrewP79** [comment]
Ok understood.
I don't think i will be able to try to implement it. 
Hope you can add it soon. thank you very much.
