### ISSUE TITLE
Migration to Arduino Core 3.x

### ISSUE THREAD

**Issue by JiriBilek** [JiriBilek/ESP_ATMod#23]
So far, the version 0.3.x was compiled with the old core v. 2.7.4.
The current core 3.0.2 introduced some breaking changes. This issue will address them.

1. ESP_ATMod does not reconnect to APs (https://github.com/JiriBilek/ESP_ATMod/issues/11)
2. Bad AT+CIPSTATUS (reply `+CIPSTATUS:2,"SSL","(IP unset)",0,0,0`) after connecting to and transferring data from web server.

The changes will be made to the branch Core_3 (https://github.com/JiriBilek/ESP_ATMod/tree/Core_3). They will result in a new version (probably 0.4).

**Comment by JAndrassy** [comment]
I use 3.0.2. I don't use SSL connection so I can't comment about that part.

I was expecting problems with automatic joining AP at start, because I know it is off by default in 3.0+, but they didn't occur. I assumed because of how WiFiEspAT library's SetupPersistentWiFiConnection example, which I use for it,  works. And I hade to run it multiple times as I switched between normal AT firmware and ESP_ATMod to compare results.

**Comment by JiriBilek** [comment]
> 2\. Bad AT+CIPSTATUS (reply `+CIPSTATUS:2,"SSL","(IP unset)",0,0,0`) after connecting to and transferring data from web server.

The problem is in the core. I have reported it.

**Comment by JAndrassy** [comment]
I can't replicate 1)
I erased the flash. uploaded ESP_ATMod built with 3.0.2 with the Erase setting "Sketch + WiFi Settings". I run AT+CWMODE=1 and AT+CWJAP for my WiFi. I reset the esp8266 and it joins the AP at start.

**Comment by JiriBilek** [comment]
With the update of core to 3.1 problems appeared:

`error: use of deleted function 'BearSSL::X509List& BearSSL::X509List::operator=(const BearSSL::X509List&)'`
https://github.com/JiriBilek/ESP_ATMod/blob/1ecacadb6e8897af5acc2ba8980fc1891356394a/ESP_ATMod/command.cpp#L2950

`warning: 'WiFiClient WiFiServer::available(uint8_t*)' is deprecated: Renamed to accept(). [-Wdeprecated-declarations]`
https://github.com/JiriBilek/ESP_ATMod/blob/1ecacadb6e8897af5acc2ba8980fc1891356394a/ESP_ATMod/ESP_ATMod.ino#L416

**Comment by JAndrassy** [comment]
the warning is expected. I made the 'rename' of available() to accept() in the ESP8266WiFi library. but it is just a warning

**Comment by JiriBilek** [comment]
Resolved by #31
